### ISSUE TITLE
Deploy ssrs project from Visual Studio 2017 doesn't work

### ISSUE THREAD

**Issue by EddyPeng** [timabell/ssrs-powershell-deploy#23]
Using older version Deploy-SSRSproject.ps1 to deploy older version ssrs project works fine, but after upgrading ssrs poject to Visual Studio 2017, the Powershell script Deploy-SSRSproject.ps1 doesn't work any longer, which doesn't show any error but doesn't deploy ssrs project to reporting server either, I also downloaded your latest powershell script and tried to use Publish-SSRSProject.ps1 to deploy the VS2017 Reporting project, it doesn't show any error and doesn't deploy the ssrs project either.

**Comment by jlrodriguesPrimeIt** [comment]
pull request pending of approval related to this issue

**Comment by jacktkeys** [comment]
@timabell Any way we could get this merged? I love your module. Just need it to support VS 2017.

**Comment by timabell** [comment]
#24

**Comment by timabell** [comment]
done
