### ISSUE TITLE
ignores OverwriteDataSources setting in project

### ISSUE THREAD

**Issue by timabell** [timabell/ssrs-powershell-deploy#3]
currently won't overwrite regardless of this setting according to my testing

**Comment by sasha2002** [comment]
where you set this settings?

**Comment by timabell** [comment]
right-click your reports project in visual studio, click properties

![ssrs report props overwrite](https://cloud.githubusercontent.com/assets/19378/7473107/66761ca2-f330-11e4-869e-25bc26b706fb.png)

**Comment by timabell** [comment]
see also issue #4

**Comment by ivanbportugal** [comment]
Need to add an if else on this line if the Overwrite switch is set in the beginning of the script

https://github.com/timabell/ssrs-powershell-deploy/blob/master/Deploy-SSRSProject/Deploy-SSRSProject.ps1#L287

Maybe something like:

```
if($OverwriteDataSources) {
    $DataSource = New-SSRSDataSource -Proxy $Proxy -RdsPath $RdsPath -Folder $DataSourceFolder -Overwrite
} else {
    $DataSource = New-SSRSDataSource -Proxy $Proxy -RdsPath $RdsPath -Folder $DataSourceFolder
}
