### ISSUE TITLE
The report server cannot process the report or shared dataset

### ISSUE THREAD

**Issue by timabell** [timabell/ssrs-powershell-deploy#5]
deploy now runs without error, but running the freshly deployed report gives me

> The report server cannot process the report or shared dataset. The shared data source 'XXXXData' for the report server or SharePoint site is not valid. Browse to the server or site and select a shared data source. (rsInvalidDataSourceReference)

**Comment by LouOtway** [comment]
We've managed to work around this problem by taking the previous version and, when the invalid data source throws an exception (see: https://github.com/timabell/ssrs-powershell-deploy/issues/2), catching it and re-deploying.

**Comment by timabell** [comment]
@LouOtway so you mean the older version of this script correctly fixed-up the datasource for you?

Dang. Flail.

Incidentally the web ui for the report says "The shared data source reference is no longer valid" with a yellow exclamation sign.

**Comment by LouOtway** [comment]
Hi Tim

Our workaround was to use the older version and run the deploy script
twice, catching the first exception.

Other than that it's great, we loved not having to mess about with that
broken web api.

Cheers

**Comment by timabell** [comment]
I've just pushed some commits that add a test ssrs project, which also breaks, thus eliminating anything to do with my client's project.

**Comment by timabell** [comment]
I agree, oh and I didn't originally write this script, I just put it on github so it was possible to work on it.

**Comment by timabell** [comment]
stepping through I see that although `$DataSources` is populated, `SetItemDataSources()` isn't being called.

https://github.com/timabell/ssrs-powershell-deploy/blob/bbd287f80f2a876b1d99f098e7aa14f7be1ee71f/Deploy-SSRSProject/Deploy-SSRSProject.ps1#L232-L234

**Comment by timabell** [comment]
Powerhell is such a horrible language. All fixed, it was just me and my size 9s trampling all over the script without understanding it.
